# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'settingsWindow_alpha_v1.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SettingsWindow(object):
    def setupUi(self, SettingsWindow):
        SettingsWindow.setObjectName("SettingsWindow")
        SettingsWindow.resize(715, 737)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(SettingsWindow.sizePolicy().hasHeightForWidth())
        SettingsWindow.setSizePolicy(sizePolicy)
        SettingsWindow.setMinimumSize(QtCore.QSize(0, 600))
        SettingsWindow.setAcceptDrops(False)
        SettingsWindow.setAutoFillBackground(False)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(SettingsWindow)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.settingsTabs = QtWidgets.QTabWidget(SettingsWindow)
        self.settingsTabs.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.settingsTabs.sizePolicy().hasHeightForWidth())
        self.settingsTabs.setSizePolicy(sizePolicy)
        self.settingsTabs.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.settingsTabs.setAutoFillBackground(True)
        self.settingsTabs.setObjectName("settingsTabs")
        self.main_tab_4 = QtWidgets.QWidget()
        self.main_tab_4.setObjectName("main_tab_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.main_tab_4)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.sweepTypeTabs_4 = QtWidgets.QTabWidget(self.main_tab_4)
        self.sweepTypeTabs_4.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sweepTypeTabs_4.sizePolicy().hasHeightForWidth())
        self.sweepTypeTabs_4.setSizePolicy(sizePolicy)
        self.sweepTypeTabs_4.setMinimumSize(QtCore.QSize(250, 100))
        self.sweepTypeTabs_4.setMaximumSize(QtCore.QSize(16777215, 300))
        self.sweepTypeTabs_4.setObjectName("sweepTypeTabs_4")
        self.linear_tab_4 = QtWidgets.QWidget()
        self.linear_tab_4.setObjectName("linear_tab_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.linear_tab_4)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gridLayout_linear_4 = QtWidgets.QGridLayout()
        self.gridLayout_linear_4.setObjectName("gridLayout_linear_4")
        self.start_label_4 = QtWidgets.QLabel(self.linear_tab_4)
        self.start_label_4.setObjectName("start_label_4")
        self.gridLayout_linear_4.addWidget(self.start_label_4, 0, 0, 1, 1)
        self.comboBox_4 = QtWidgets.QComboBox(self.linear_tab_4)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.gridLayout_linear_4.addWidget(self.comboBox_4, 2, 1, 1, 1)
        self.MHz_label_7 = QtWidgets.QLabel(self.linear_tab_4)
        self.MHz_label_7.setObjectName("MHz_label_7")
        self.gridLayout_linear_4.addWidget(self.MHz_label_7, 1, 2, 1, 1)
        self.stop_label_4 = QtWidgets.QLabel(self.linear_tab_4)
        self.stop_label_4.setObjectName("stop_label_4")
        self.gridLayout_linear_4.addWidget(self.stop_label_4, 1, 0, 1, 1)
        self.points_label_4 = QtWidgets.QLabel(self.linear_tab_4)
        self.points_label_4.setObjectName("points_label_4")
        self.gridLayout_linear_4.addWidget(self.points_label_4, 2, 0, 1, 1)
        self.lineEdit_start_4 = QtWidgets.QLineEdit(self.linear_tab_4)
        self.lineEdit_start_4.setObjectName("lineEdit_start_4")
        self.gridLayout_linear_4.addWidget(self.lineEdit_start_4, 0, 1, 1, 1)
        self.MHz_label_8 = QtWidgets.QLabel(self.linear_tab_4)
        self.MHz_label_8.setObjectName("MHz_label_8")
        self.gridLayout_linear_4.addWidget(self.MHz_label_8, 0, 2, 1, 1)
        self.lineEdit_stop_4 = QtWidgets.QLineEdit(self.linear_tab_4)
        self.lineEdit_stop_4.setObjectName("lineEdit_stop_4")
        self.gridLayout_linear_4.addWidget(self.lineEdit_stop_4, 1, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayout_linear_4)
        self.sweepTypeTabs_4.addTab(self.linear_tab_4, "")
        self.list_tab_4 = QtWidgets.QWidget()
        self.list_tab_4.setObjectName("list_tab_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.list_tab_4)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.gridLayout_list_5 = QtWidgets.QGridLayout()
        self.gridLayout_list_5.setObjectName("gridLayout_list_5")
        self.list_label_5 = QtWidgets.QLabel(self.list_tab_4)
        self.list_label_5.setObjectName("list_label_5")
        self.gridLayout_list_5.addWidget(self.list_label_5, 0, 0, 1, 1)
        self.lineEdit_list_5 = QtWidgets.QLineEdit(self.list_tab_4)
        self.lineEdit_list_5.setObjectName("lineEdit_list_5")
        self.gridLayout_list_5.addWidget(self.lineEdit_list_5, 0, 1, 1, 1)
        self.list_MHz_label_5 = QtWidgets.QLabel(self.list_tab_4)
        self.list_MHz_label_5.setObjectName("list_MHz_label_5")
        self.gridLayout_list_5.addWidget(self.list_MHz_label_5, 0, 2, 1, 1)
        self.verticalLayout_11.addLayout(self.gridLayout_list_5)
        self.sweepTypeTabs_4.addTab(self.list_tab_4, "")
        self.verticalLayout_6.addWidget(self.sweepTypeTabs_4)
        self.global_settings_frame_4 = QtWidgets.QFrame(self.main_tab_4)
        self.global_settings_frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.global_settings_frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.global_settings_frame_4.setObjectName("global_settings_frame_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.global_settings_frame_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.gridLayout_global_settings_7 = QtWidgets.QGridLayout()
        self.gridLayout_global_settings_7.setObjectName("gridLayout_global_settings_7")
        self.cont_radioButton_7 = QtWidgets.QRadioButton(self.global_settings_frame_4)
        self.cont_radioButton_7.setObjectName("cont_radioButton_7")
        self.posMov_buttonGroup = QtWidgets.QButtonGroup(SettingsWindow)
        self.posMov_buttonGroup.setObjectName("posMov_buttonGroup")
        self.posMov_buttonGroup.addButton(self.cont_radioButton_7)
        self.gridLayout_global_settings_7.addWidget(self.cont_radioButton_7, 3, 1, 1, 1)
        self.Averaging_comboBox_7 = QtWidgets.QComboBox(self.global_settings_frame_4)
        self.Averaging_comboBox_7.setObjectName("Averaging_comboBox_7")
        self.Averaging_comboBox_7.addItem("")
        self.Averaging_comboBox_7.addItem("")
        self.gridLayout_global_settings_7.addWidget(self.Averaging_comboBox_7, 2, 1, 1, 1)
        self.res_doubleSpinBox_7 = QtWidgets.QDoubleSpinBox(self.global_settings_frame_4)
        self.res_doubleSpinBox_7.setMaximum(5.0)
        self.res_doubleSpinBox_7.setSingleStep(0.01)
        self.res_doubleSpinBox_7.setObjectName("res_doubleSpinBox_7")
        self.gridLayout_global_settings_7.addWidget(self.res_doubleSpinBox_7, 4, 1, 1, 1)
        self.Impedance_label_7 = QtWidgets.QLabel(self.global_settings_frame_4)
        self.Impedance_label_7.setObjectName("Impedance_label_7")
        self.gridLayout_global_settings_7.addWidget(self.Impedance_label_7, 0, 0, 1, 1)
        self.Impedance_radioButton_n_7 = QtWidgets.QRadioButton(self.global_settings_frame_4)
        self.Impedance_radioButton_n_7.setChecked(True)
        self.Impedance_radioButton_n_7.setObjectName("Impedance_radioButton_n_7")
        self.Impedance_buttonGroup = QtWidgets.QButtonGroup(SettingsWindow)
        self.Impedance_buttonGroup.setObjectName("Impedance_buttonGroup")
        self.Impedance_buttonGroup.addButton(self.Impedance_radioButton_n_7)
        self.gridLayout_global_settings_7.addWidget(self.Impedance_radioButton_n_7, 0, 2, 1, 1)
        self.res_label_7 = QtWidgets.QLabel(self.global_settings_frame_4)
        self.res_label_7.setObjectName("res_label_7")
        self.gridLayout_global_settings_7.addWidget(self.res_label_7, 4, 0, 1, 1)
        self.Impedance_radioButton_y_7 = QtWidgets.QRadioButton(self.global_settings_frame_4)
        self.Impedance_radioButton_y_7.setObjectName("Impedance_radioButton_y_7")
        self.Impedance_buttonGroup.addButton(self.Impedance_radioButton_y_7)
        self.gridLayout_global_settings_7.addWidget(self.Impedance_radioButton_y_7, 0, 1, 1, 1)
        self.Calibration_radioButton_y_7 = QtWidgets.QRadioButton(self.global_settings_frame_4)
        self.Calibration_radioButton_y_7.setObjectName("Calibration_radioButton_y_7")
        self.Calibration_buttonGroup_2 = QtWidgets.QButtonGroup(SettingsWindow)
        self.Calibration_buttonGroup_2.setObjectName("Calibration_buttonGroup_2")
        self.Calibration_buttonGroup_2.addButton(self.Calibration_radioButton_y_7)
        self.gridLayout_global_settings_7.addWidget(self.Calibration_radioButton_y_7, 1, 1, 1, 1)
        self.Calibration_radioButton_n_7 = QtWidgets.QRadioButton(self.global_settings_frame_4)
        self.Calibration_radioButton_n_7.setChecked(True)
        self.Calibration_radioButton_n_7.setObjectName("Calibration_radioButton_n_7")
        self.Calibration_buttonGroup_2.addButton(self.Calibration_radioButton_n_7)
        self.gridLayout_global_settings_7.addWidget(self.Calibration_radioButton_n_7, 1, 2, 1, 1)
        self.posMov_label_7 = QtWidgets.QLabel(self.global_settings_frame_4)
        self.posMov_label_7.setObjectName("posMov_label_7")
        self.gridLayout_global_settings_7.addWidget(self.posMov_label_7, 3, 0, 1, 1)
        self.Averaging_label_7 = QtWidgets.QLabel(self.global_settings_frame_4)
        self.Averaging_label_7.setObjectName("Averaging_label_7")
        self.gridLayout_global_settings_7.addWidget(self.Averaging_label_7, 2, 0, 1, 1)
        self.discrete_radioButton_7 = QtWidgets.QRadioButton(self.global_settings_frame_4)
        self.discrete_radioButton_7.setChecked(True)
        self.discrete_radioButton_7.setObjectName("discrete_radioButton_7")
        self.posMov_buttonGroup.addButton(self.discrete_radioButton_7)
        self.gridLayout_global_settings_7.addWidget(self.discrete_radioButton_7, 3, 2, 1, 1)
        self.Calibration_label_7 = QtWidgets.QLabel(self.global_settings_frame_4)
        self.Calibration_label_7.setObjectName("Calibration_label_7")
        self.gridLayout_global_settings_7.addWidget(self.Calibration_label_7, 1, 0, 1, 1)
        self.res_label_degrees_7 = QtWidgets.QLabel(self.global_settings_frame_4)
        self.res_label_degrees_7.setObjectName("res_label_degrees_7")
        self.gridLayout_global_settings_7.addWidget(self.res_label_degrees_7, 4, 2, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_global_settings_7)
        self.verticalLayout_6.addWidget(self.global_settings_frame_4)
        self.hardware_settings_gridLayout_6 = QtWidgets.QGridLayout()
        self.hardware_settings_gridLayout_6.setObjectName("hardware_settings_gridLayout_6")
        self.pos_alias_lineEdit_6 = QtWidgets.QLineEdit(self.main_tab_4)
        self.pos_alias_lineEdit_6.setObjectName("pos_alias_lineEdit_6")
        self.hardware_settings_gridLayout_6.addWidget(self.pos_alias_lineEdit_6, 1, 1, 1, 1)
        self.BaudRate_label_6 = QtWidgets.QLabel(self.main_tab_4)
        self.BaudRate_label_6.setObjectName("BaudRate_label_6")
        self.hardware_settings_gridLayout_6.addWidget(self.BaudRate_label_6, 2, 0, 1, 1)
        self.pos_Alias_label_6 = QtWidgets.QLabel(self.main_tab_4)
        self.pos_Alias_label_6.setObjectName("pos_Alias_label_6")
        self.hardware_settings_gridLayout_6.addWidget(self.pos_Alias_label_6, 1, 0, 1, 1)
        self.GPIB_addr_comboBox_6 = QtWidgets.QComboBox(self.main_tab_4)
        self.GPIB_addr_comboBox_6.setObjectName("GPIB_addr_comboBox_6")
        self.hardware_settings_gridLayout_6.addWidget(self.GPIB_addr_comboBox_6, 0, 1, 1, 1)
        self.GPIB_addr_label_6 = QtWidgets.QLabel(self.main_tab_4)
        self.GPIB_addr_label_6.setObjectName("GPIB_addr_label_6")
        self.hardware_settings_gridLayout_6.addWidget(self.GPIB_addr_label_6, 0, 0, 1, 1)
        self.BaudRate_comboBox_6 = QtWidgets.QComboBox(self.main_tab_4)
        self.BaudRate_comboBox_6.setObjectName("BaudRate_comboBox_6")
        self.BaudRate_comboBox_6.addItem("")
        self.BaudRate_comboBox_6.addItem("")
        self.BaudRate_comboBox_6.addItem("")
        self.BaudRate_comboBox_6.addItem("")
        self.BaudRate_comboBox_6.addItem("")
        self.hardware_settings_gridLayout_6.addWidget(self.BaudRate_comboBox_6, 2, 1, 1, 1)
        self.verticalLayout_6.addLayout(self.hardware_settings_gridLayout_6)
        self.settings_bttns_frame_4 = QtWidgets.QFrame(self.main_tab_4)
        self.settings_bttns_frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.settings_bttns_frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.settings_bttns_frame_4.setObjectName("settings_bttns_frame_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.settings_bttns_frame_4)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.settings_buttn_vlayout_5 = QtWidgets.QVBoxLayout()
        self.settings_buttn_vlayout_5.setObjectName("settings_buttn_vlayout_5")
        self.settings_cancel_pushButton_5 = QtWidgets.QPushButton(self.settings_bttns_frame_4)
        self.settings_cancel_pushButton_5.setObjectName("settings_cancel_pushButton_5")
        self.settings_buttn_vlayout_5.addWidget(self.settings_cancel_pushButton_5)
        self.settings_submit_pushButton_5 = QtWidgets.QPushButton(self.settings_bttns_frame_4)
        self.settings_submit_pushButton_5.setObjectName("settings_submit_pushButton_5")
        self.settings_buttn_vlayout_5.addWidget(self.settings_submit_pushButton_5)
        self.horizontalLayout.addLayout(self.settings_buttn_vlayout_5)
        self.verticalLayout_6.addWidget(self.settings_bttns_frame_4)
        self.verticalLayout_6.setStretch(0, 1)
        self.verticalLayout_6.setStretch(1, 1)
        self.verticalLayout_6.setStretch(2, 1)
        self.verticalLayout_6.setStretch(3, 1)
        self.settingsTabs.addTab(self.main_tab_4, "")
        self.positioner_tab_4 = QtWidgets.QWidget()
        self.positioner_tab_4.setObjectName("positioner_tab_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.positioner_tab_4)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.arrows_frame_4 = QtWidgets.QFrame(self.positioner_tab_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arrows_frame_4.sizePolicy().hasHeightForWidth())
        self.arrows_frame_4.setSizePolicy(sizePolicy)
        self.arrows_frame_4.setFocusPolicy(QtCore.Qt.NoFocus)
        self.arrows_frame_4.setAutoFillBackground(False)
        self.arrows_frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.arrows_frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.arrows_frame_4.setObjectName("arrows_frame_4")
        self.gridLayout = QtWidgets.QGridLayout(self.arrows_frame_4)
        self.gridLayout.setObjectName("gridLayout")
        self.up_toolButton_4 = QtWidgets.QToolButton(self.arrows_frame_4)
        self.up_toolButton_4.setArrowType(QtCore.Qt.UpArrow)
        self.up_toolButton_4.setObjectName("up_toolButton_4")
        self.gridLayout.addWidget(self.up_toolButton_4, 0, 1, 1, 1)
        self.left_toolButton_4 = QtWidgets.QToolButton(self.arrows_frame_4)
        self.left_toolButton_4.setArrowType(QtCore.Qt.LeftArrow)
        self.left_toolButton_4.setObjectName("left_toolButton_4")
        self.gridLayout.addWidget(self.left_toolButton_4, 1, 0, 1, 1)
        self.right_toolButton_4 = QtWidgets.QToolButton(self.arrows_frame_4)
        self.right_toolButton_4.setArrowType(QtCore.Qt.RightArrow)
        self.right_toolButton_4.setObjectName("right_toolButton_4")
        self.gridLayout.addWidget(self.right_toolButton_4, 1, 2, 1, 1)
        self.down_toolButton_4 = QtWidgets.QToolButton(self.arrows_frame_4)
        self.down_toolButton_4.setArrowType(QtCore.Qt.DownArrow)
        self.down_toolButton_4.setObjectName("down_toolButton_4")
        self.gridLayout.addWidget(self.down_toolButton_4, 2, 1, 1, 1)
        self.verticalLayout_10.addWidget(self.arrows_frame_4)
        self.pos_display_layout_4 = QtWidgets.QGridLayout()
        self.pos_display_layout_4.setObjectName("pos_display_layout_4")
        self.pan_frame_4 = QtWidgets.QFrame(self.positioner_tab_4)
        self.pan_frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pan_frame_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.pan_frame_4.setObjectName("pan_frame_4")
        self.pan_label_4 = QtWidgets.QLabel(self.pan_frame_4)
        self.pan_label_4.setGeometry(QtCore.QRect(50, 20, 31, 16))
        self.pan_label_4.setObjectName("pan_label_4")
        self.pos_display_layout_4.addWidget(self.pan_frame_4, 0, 0, 1, 1)
        self.tilt_lcdNumber_4 = QtWidgets.QLCDNumber(self.positioner_tab_4)
        self.tilt_lcdNumber_4.setSmallDecimalPoint(True)
        self.tilt_lcdNumber_4.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.tilt_lcdNumber_4.setObjectName("tilt_lcdNumber_4")
        self.pos_display_layout_4.addWidget(self.tilt_lcdNumber_4, 1, 1, 1, 1)
        self.tilt_frame_4 = QtWidgets.QFrame(self.positioner_tab_4)
        self.tilt_frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tilt_frame_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tilt_frame_4.setObjectName("tilt_frame_4")
        self.tilt_label_4 = QtWidgets.QLabel(self.tilt_frame_4)
        self.tilt_label_4.setGeometry(QtCore.QRect(60, 20, 21, 21))
        self.tilt_label_4.setObjectName("tilt_label_4")
        self.pos_display_layout_4.addWidget(self.tilt_frame_4, 0, 1, 1, 1)
        self.pan_lcdNumber_4 = QtWidgets.QLCDNumber(self.positioner_tab_4)
        self.pan_lcdNumber_4.setSmallDecimalPoint(True)
        self.pan_lcdNumber_4.setObjectName("pan_lcdNumber_4")
        self.pos_display_layout_4.addWidget(self.pan_lcdNumber_4, 1, 0, 1, 1)
        self.verticalLayout_10.addLayout(self.pos_display_layout_4)
        self.offsetBttns_layout_4 = QtWidgets.QVBoxLayout()
        self.offsetBttns_layout_4.setObjectName("offsetBttns_layout_4")
        self.getCurrentOffsets_Button_4 = QtWidgets.QPushButton(self.positioner_tab_4)
        self.getCurrentOffsets_Button_4.setObjectName("getCurrentOffsets_Button_4")
        self.offsetBttns_layout_4.addWidget(self.getCurrentOffsets_Button_4)
        self.zeroOffsets_Button_4 = QtWidgets.QPushButton(self.positioner_tab_4)
        self.zeroOffsets_Button_4.setObjectName("zeroOffsets_Button_4")
        self.offsetBttns_layout_4.addWidget(self.zeroOffsets_Button_4)
        self.setAngleOffsetButton_4 = QtWidgets.QPushButton(self.positioner_tab_4)
        self.setAngleOffsetButton_4.setObjectName("setAngleOffsetButton_4")
        self.offsetBttns_layout_4.addWidget(self.setAngleOffsetButton_4)
        self.aligntoCenterButton_4 = QtWidgets.QPushButton(self.positioner_tab_4)
        self.aligntoCenterButton_4.setObjectName("aligntoCenterButton_4")
        self.offsetBttns_layout_4.addWidget(self.aligntoCenterButton_4)
        self.verticalLayout_10.addLayout(self.offsetBttns_layout_4)
        self.settingsTabs.addTab(self.positioner_tab_4, "")
        self.verticalLayout_5.addWidget(self.settingsTabs)

        self.retranslateUi(SettingsWindow)
        self.settingsTabs.setCurrentIndex(1)
        self.sweepTypeTabs_4.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(SettingsWindow)

    def retranslateUi(self, SettingsWindow):
        _translate = QtCore.QCoreApplication.translate
        SettingsWindow.setWindowTitle(_translate("SettingsWindow", "Settings Window"))
        self.start_label_4.setText(_translate("SettingsWindow", "Start : "))
        self.comboBox_4.setItemText(0, _translate("SettingsWindow", "201"))
        self.comboBox_4.setItemText(1, _translate("SettingsWindow", "401"))
        self.comboBox_4.setItemText(2, _translate("SettingsWindow", "801"))
        self.comboBox_4.setItemText(3, _translate("SettingsWindow", "1601"))
        self.MHz_label_7.setText(_translate("SettingsWindow", "MHz"))
        self.stop_label_4.setText(_translate("SettingsWindow", "Stop :"))
        self.points_label_4.setText(_translate("SettingsWindow", "Points : "))
        self.MHz_label_8.setText(_translate("SettingsWindow", "MHz"))
        self.sweepTypeTabs_4.setTabText(self.sweepTypeTabs_4.indexOf(self.linear_tab_4), _translate("SettingsWindow", "Linear"))
        self.list_label_5.setText(_translate("SettingsWindow", "Frequencies : "))
        self.list_MHz_label_5.setText(_translate("SettingsWindow", "MHz"))
        self.sweepTypeTabs_4.setTabText(self.sweepTypeTabs_4.indexOf(self.list_tab_4), _translate("SettingsWindow", "List"))
        self.cont_radioButton_7.setText(_translate("SettingsWindow", "continous"))
        self.Averaging_comboBox_7.setItemText(0, _translate("SettingsWindow", "8"))
        self.Averaging_comboBox_7.setItemText(1, _translate("SettingsWindow", "16"))
        self.Impedance_label_7.setText(_translate("SettingsWindow", "Impedance : "))
        self.Impedance_radioButton_n_7.setText(_translate("SettingsWindow", "No"))
        self.res_label_7.setText(_translate("SettingsWindow", "Resolution : "))
        self.Impedance_radioButton_y_7.setText(_translate("SettingsWindow", "Yes"))
        self.Calibration_radioButton_y_7.setText(_translate("SettingsWindow", "Yes "))
        self.Calibration_radioButton_n_7.setText(_translate("SettingsWindow", "No"))
        self.posMov_label_7.setText(_translate("SettingsWindow", "Positioner Movment : "))
        self.Averaging_label_7.setText(_translate("SettingsWindow", "Averaging : "))
        self.discrete_radioButton_7.setText(_translate("SettingsWindow", "discrete"))
        self.Calibration_label_7.setText(_translate("SettingsWindow", "Calibration : "))
        self.res_label_degrees_7.setText(_translate("SettingsWindow", "degrees"))
        self.BaudRate_label_6.setText(_translate("SettingsWindow", "Baud Rate :"))
        self.pos_Alias_label_6.setText(_translate("SettingsWindow", "Positioner Alias : "))
        self.GPIB_addr_label_6.setText(_translate("SettingsWindow", "GPIB Address : "))
        self.BaudRate_comboBox_6.setItemText(0, _translate("SettingsWindow", "1200"))
        self.BaudRate_comboBox_6.setItemText(1, _translate("SettingsWindow", "2400"))
        self.BaudRate_comboBox_6.setItemText(2, _translate("SettingsWindow", "4800"))
        self.BaudRate_comboBox_6.setItemText(3, _translate("SettingsWindow", "9600"))
        self.BaudRate_comboBox_6.setItemText(4, _translate("SettingsWindow", "14400"))
        self.settings_cancel_pushButton_5.setText(_translate("SettingsWindow", "Cancel"))
        self.settings_submit_pushButton_5.setText(_translate("SettingsWindow", "Submit"))
        self.settingsTabs.setTabText(self.settingsTabs.indexOf(self.main_tab_4), _translate("SettingsWindow", "Main Settings"))
        self.up_toolButton_4.setText(_translate("SettingsWindow", "..."))
        self.up_toolButton_4.setShortcut(_translate("SettingsWindow", "W"))
        self.left_toolButton_4.setText(_translate("SettingsWindow", "..."))
        self.left_toolButton_4.setShortcut(_translate("SettingsWindow", "A"))
        self.right_toolButton_4.setText(_translate("SettingsWindow", "..."))
        self.right_toolButton_4.setShortcut(_translate("SettingsWindow", "D"))
        self.down_toolButton_4.setText(_translate("SettingsWindow", "..."))
        self.down_toolButton_4.setShortcut(_translate("SettingsWindow", "S"))
        self.pan_label_4.setText(_translate("SettingsWindow", "Pan"))
        self.tilt_label_4.setText(_translate("SettingsWindow", "Tilt"))
        self.getCurrentOffsets_Button_4.setText(_translate("SettingsWindow", "Get Current Offsets"))
        self.zeroOffsets_Button_4.setText(_translate("SettingsWindow", "Zero Offsets"))
        self.setAngleOffsetButton_4.setText(_translate("SettingsWindow", "Set Angle Offsets"))
        self.aligntoCenterButton_4.setText(_translate("SettingsWindow", "Align to Center"))
        self.settingsTabs.setTabText(self.settingsTabs.indexOf(self.positioner_tab_4), _translate("SettingsWindow", "Positioner Settings"))
