# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'graph_mode_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setEnabled(True)
        Form.resize(140, 95)
        Form.setMaximumSize(QtCore.QSize(1000, 1000))
        self.horizontalLayout = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.graph_mode_groupBox = QtWidgets.QGroupBox(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graph_mode_groupBox.sizePolicy().hasHeightForWidth())
        self.graph_mode_groupBox.setSizePolicy(sizePolicy)
        self.graph_mode_groupBox.setMinimumSize(QtCore.QSize(122, 54))
        self.graph_mode_groupBox.setMaximumSize(QtCore.QSize(122, 77))
        self.graph_mode_groupBox.setFlat(False)
        self.graph_mode_groupBox.setCheckable(False)
        self.graph_mode_groupBox.setChecked(False)
        self.graph_mode_groupBox.setObjectName("graph_mode_groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.graph_mode_groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.s21_imp_comboBox = QtWidgets.QComboBox(self.graph_mode_groupBox)
        self.s21_imp_comboBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.s21_imp_comboBox.sizePolicy().hasHeightForWidth())
        self.s21_imp_comboBox.setSizePolicy(sizePolicy)
        self.s21_imp_comboBox.setMinimumSize(QtCore.QSize(0, 19))
        self.s21_imp_comboBox.setMaximumSize(QtCore.QSize(102, 19))
        self.s21_imp_comboBox.setEditable(False)
        self.s21_imp_comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.s21_imp_comboBox.setFrame(True)
        self.s21_imp_comboBox.setObjectName("s21_imp_comboBox")
        self.s21_imp_comboBox.addItem("")
        self.s21_imp_comboBox.addItem("")
        self.verticalLayout.addWidget(self.s21_imp_comboBox)
        self.polar_rect_comboBox = QtWidgets.QComboBox(self.graph_mode_groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.polar_rect_comboBox.sizePolicy().hasHeightForWidth())
        self.polar_rect_comboBox.setSizePolicy(sizePolicy)
        self.polar_rect_comboBox.setMinimumSize(QtCore.QSize(0, 19))
        self.polar_rect_comboBox.setMaximumSize(QtCore.QSize(102, 19))
        self.polar_rect_comboBox.setSizeAdjustPolicy(QtWidgets.QComboBox.AdjustToContents)
        self.polar_rect_comboBox.setFrame(True)
        self.polar_rect_comboBox.setObjectName("polar_rect_comboBox")
        self.polar_rect_comboBox.addItem("")
        self.polar_rect_comboBox.addItem("")
        self.verticalLayout.addWidget(self.polar_rect_comboBox)
        self.horizontalLayout.addWidget(self.graph_mode_groupBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.graph_mode_groupBox.setTitle(_translate("Form", "Graph Mode"))
        self.s21_imp_comboBox.setItemText(0, _translate("Form", "S21"))
        self.s21_imp_comboBox.setItemText(1, _translate("Form", "Impedance"))
        self.polar_rect_comboBox.setItemText(0, _translate("Form", "Polar"))
        self.polar_rect_comboBox.setItemText(1, _translate("Form", "Rectangular"))
