# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'meas_display_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(442, 59)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.MeasDisplaywidget = QtWidgets.QWidget(Form)
        self.MeasDisplaywidget.setObjectName("MeasDisplaywidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.MeasDisplaywidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.azimuth_label = QtWidgets.QLabel(self.MeasDisplaywidget)
        self.azimuth_label.setObjectName("azimuth_label")
        self.horizontalLayout.addWidget(self.azimuth_label)
        self.az_lcdNumber = QtWidgets.QLCDNumber(self.MeasDisplaywidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.az_lcdNumber.sizePolicy().hasHeightForWidth())
        self.az_lcdNumber.setSizePolicy(sizePolicy)
        self.az_lcdNumber.setMinimumSize(QtCore.QSize(149, 41))
        self.az_lcdNumber.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.az_lcdNumber.setFrameShadow(QtWidgets.QFrame.Raised)
        self.az_lcdNumber.setSmallDecimalPoint(False)
        self.az_lcdNumber.setDigitCount(7)
        self.az_lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.az_lcdNumber.setObjectName("az_lcdNumber")
        self.horizontalLayout.addWidget(self.az_lcdNumber)
        self.elevation_label = QtWidgets.QLabel(self.MeasDisplaywidget)
        self.elevation_label.setObjectName("elevation_label")
        self.horizontalLayout.addWidget(self.elevation_label)
        self.el_lcdNumber = QtWidgets.QLCDNumber(self.MeasDisplaywidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.el_lcdNumber.sizePolicy().hasHeightForWidth())
        self.el_lcdNumber.setSizePolicy(sizePolicy)
        self.el_lcdNumber.setMinimumSize(QtCore.QSize(149, 41))
        self.el_lcdNumber.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.el_lcdNumber.setFrameShadow(QtWidgets.QFrame.Raised)
        self.el_lcdNumber.setSmallDecimalPoint(False)
        self.el_lcdNumber.setDigitCount(7)
        self.el_lcdNumber.setSegmentStyle(QtWidgets.QLCDNumber.Filled)
        self.el_lcdNumber.setObjectName("el_lcdNumber")
        self.horizontalLayout.addWidget(self.el_lcdNumber)
        self.verticalLayout.addWidget(self.MeasDisplaywidget)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.azimuth_label.setText(_translate("Form", "Azimuth:"))
        self.elevation_label.setText(_translate("Form", "Elevation:"))
